cart/urls.py
from django.conf.urls import url
from . import views
urlpatterns = [
    url(r'^remove/(?P<product_id>\d+)/$', views.CartRemove, name='CartRemove'),
    url(r'^add/(?P<product_id>\d+)/$', views.CartAdd, name='CartAdd'),
    url(r'^$', views.CartDetail, name='CartDetail'),
]

myshop/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'main/', include('main.urls', namespace='main')),
    url(r'^admin/', admin.site.urls),
    url(r'^cart/', include('cart.urls', namespace='cart')),
    url(r'^', include('shop.urls', namespace='shop')),
    url(r'^order/', include('orders.urls', namespace='orders')),


]

orders/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^create/$', views.OrderCreate, name='OrderCreate')
]

shop/urls.py
from django.conf.urls import url
from . import views
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    url(r'^(?P<category_slug>[-\w]+)/$', views.ProductList, name='ProductListByCategory'),
    url(r'^(?P<collection_slug>[-\w]+)/$', views.ProductList, name='ProductListByCollection'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.ProductDetail, name='ProductDetail'),
    url(r'^$', views.ProductList, name='ProductList'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms
PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]
class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Product
from .cart import Cart
from .forms import CartAddProductForm
from django.views.decorators.csrf import csrf_exempt
@require_POST
@csrf_exempt
def CartAdd(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'],
        update_quantity=cd['update'])
    return redirect('cart:CartDetail')
def CartRemove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:CartDetail')
def CartDetail(request):
    cart = Cart(request)
    return render(request, 'cart/detail.html', {'cart': cart})
def CartDetail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(
                                        initial={
                                            'quantity': item['quantity'],
                                            'update': True
                                        })
    return render(request, 'cart/detail.html', {'cart': cart})

cart/templates/cart/detail.html
{% extends "shop/base.html" %}
{% block title %}
  Ваша корзина товаров
{% endblock %}
{% block menu %}
<header class="header">
    <div class="mobile-name" style="font-size: 40px; padding-top: 20px; font-weight: bold;">D.O.T.1.2.7</div>
    <div class="mobile-icon" style="padding-top: 20px;"><img src="img/iconmonstr-menu-1.svg"></div>
    <div class="menu">
        <div class="header__left">
            <ul>
                <li><a href="#">О нас</a></li>
                <li> <a href="#" id="shop">Магазин</a>
                    <ul class="submenu" id="submenu-shop" style="margin-top: 0; top: 43px;">
                        <li><a href="/">Все</a></li>
                        <li><a href="#">Верхняя одежда</a></li>
                        <li><a href="#">Джемперы и свитеры</a></li>
                        <li><a href="#">Костюмы</a></li>
                        <li><a href="#">Деним</a></li>
                        <li><a href="#">Брюки и юбки</a></li>
                        <li><a href="#">Платья</a></li>
                    </ul>
                </li>
                <li><a href="#" id = "collections">Коллекции</a>
                    <ul class="submenu" id="submenu-collection" style="margin-top: 0; top: 43px; left: 215px;">
                        <li class="submenu_st"><a href="/">FW 18-19</a></li>
                        <li><a href="#">SS 18</a></li>
                        <li style="
                            padding-bottom: 0;
                            margin-bottom: 0;
                            "><a href="#">FW 17-18</a></li>
                    </ul>
                </li>
                <li><a href="#">SALE</a></li>
            </ul>
        </div>
        <div class="header__name"><a href="/main">DOT 1.2.7</a></div>
        <div class="header__right">
            <ul>
                <li class="search">
                    <form>
                        <input class="header__input" placeholder="Search">
                            </form>
                </li>
                <li><a href="#">Корзина</a></li>
                <li><a href="#">Войти</a></li>
                <li>
                    <select>
                        <option>руб</option>
                        <option>usd</option>
                    </select>
                </li>
            </ul>
        </div>
    </div>
</header>
{% endblock %}
{% block content %}
  <h1>Ваша корзина товаров</h1>
  <table class="cart">
    <thead>
      <tr>
        <th>Изображение</th>
        <th>Продукт</th>
        <th>Количество</th>
        <th>Удалить</th>
        <th>Полная цена</th>
        <th>Цена</th>
      </tr>
    </thead>
    <tbody>
      {% for item in cart %}
        {% with product=item.product %}
          <tr>
            <td>
              <a href="{{ product.get_absolute_url }}">
                <img src="{{ product.image.url }}" class="in_cart_img" />
              </a>
            </td>
            <td>{{ product.name }}</td>
            <td>
              <form style="border:1px;" action="{% url "cart:CartAdd" product.id %}" method="post" class="add">
              {{ item.update_quantity_form.quantity }}
              {{ item.update_quantity_form.update }}
              {% csrf_token %}
              <input type="submit" value="Обновить"></form>
            </td>
            <td><a href="{% url "cart:CartRemove" product.id %}">Удалить</a></td>
            <td class="num">{{ item.price }} руб.</td>
            <td class="num">{{ item.total_price }} руб.</td>
          </tr>
        {% endwith %}
      {% endfor %}
        <tr class="total">
          <td>Total</td>
          <td colspan="4"></td>
          <td class="num">{{ cart.get_total_price }} руб.</td>
        </tr>
    </tbody>
  </table>
  <p class="text-right">
    <a href="{% url 'shop:ProductList'%}" class="btn">Продолжить Шопинг</a>
    <a href="{% url 'orders:OrderCreate' %}" class="btn">Оформить заказ</a>
  </p>

{%endblock%}